WAV life_sfx "sfx/1up.wav" XGM 
WAV destroy_sfx "sfx/block_break.wav" XGM
WAV defeatBowser "sfx/bowser_fall.wav" XGM 
WAV coin_sfx "sfx/coin.wav" XGM 
WAV block_hit "sfx/collision.wav" XGM 
WAV bowser_fireball_sfx "sfx/fire.wav" XGM 
WAV player_fireball_sfx "sfx/fireball.wav" XGM 
WAV jump_sfx "sfx/jump.wav" XGM 
WAV pause_sfx "sfx/pause.wav" XGM 
WAV pipe_sfx "sfx/pipe.wav" XGM 
WAV item_appear "sfx/powerup_appear.wav" XGM 
WAV upgrade "sfx/powerup.wav" XGM 
WAV shell_kick "sfx/shellkick.wav" XGM 
WAV swim_sfx "sfx/swim.wav" XGM 
WAV vine_grow_sfx "sfx/vine_grow.wav" XGM